"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import useQuiz from "./store";

const inter = Inter({ subsets: ["latin"] });

// const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  quiz
}: {
  children: React.ReactNode;
  quiz: React.ReactNode;

}) {
  const config = useQuiz((state) => state.config);
  const render = config.status === "start" ? quiz : children;
  return (
    <html lang="en">
      <body className={inter.className}>{render}</body>
    </html>
  );
}
